---
- name: Create directory for authentik
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0700'
    owner: "{{ authentik_service_user }}"
    group: "{{ authentik_service_user }}"
  loop:
    - "{{ authentik_base_directory }}"
