---
- name: Edit my_app file already deployed
  ansible.builtin.replace:
    path: "{{ my_app_installed_config_file }}"
    regexp: "TEXT_TO_FIND"
    replace: "TEXT_TO_ADD"
    owner: "{{ my_app_service_user }}"
    group: "{{ my_app_service_user }}"
    mode: '0700'

- name: Deploy fresh app config file
  ansible.builtin.template:
    src: "{{ my_app_deployed_config_file }}"
    dest: "{{ my_app_dir }}/CONFIG_PATH"
    force: true
    mode: '0700'  # Ansible-Lint hates when this isn't set

- name: Own all of the my_app folder
  ansible.builtin.file:
    path: "{{ my_app_dir }}"
    state: directory
    recurse: true
    owner: '{{ my_app_service_user }}'
    group: '{{ my_app_service_user }}'
