---
# tasks file for zz_app
- name: Install dependencies
  ansible.builtin.include_tasks:
    file: "01_install_dependencies.yml"

- name: Add Service User
  ansible.builtin.include_tasks:
    file: "02_create_serviceuser.yml"

- name: Download and Install my_app
  ansible.builtin.include_tasks:
    file: "03_install_app.yml"

- name: Configure Environment
  ansible.builtin.include_tasks:
    file: "04_configure_app.yml"

- name: Deploy Services and Handle SSL
  ansible.builtin.include_tasks:
    file: "05_deploy_services.yml"
