---
# tasks file for cd_authentik
- name: Install dependencies
  ansible.builtin.include_tasks:
    file: "01_install_dependencies.yml"

- name: Add Service User
  ansible.builtin.include_tasks:
    file: "02_create_serviceuser.yml"

- name: Configure Environment
  ansible.builtin.include_tasks:
    file: "03_configure_app.yml"

- name: Download and Install Authentik
  ansible.builtin.include_tasks:
    file: "04_install_app.yml"

- name: Deploy Services and Handle SSL
  ansible.builtin.include_tasks:
    file: "05_deploy_services.yml"

- name: Print completion message
  ansible.builtin.debug:
    msg:
      - "Congrats! Authentik is installed at http://{{ ansible_default_ipv4.address }}/if/flow/initial-setup/"
      - "Default user is akadmin"
    verbosity: 0
